---

- hosts: all
  become: true
  tasks: 


  - name: install apache2 and php packages for debian
    apt:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
